# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestW06Test():
  def setup_method(self, method):
    options = Options()
    options.add_argument("--headless=new")
    self.driver = webdriver.Chrome(options=options)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_directoryListTest(self):
    self.driver.get("http://localhost:5500/teton/1.6/directory.html")
    self.driver.set_window_size(1200, 800)
    self.driver.find_element(By.XPATH, "//button[normalize-space()=\'LIST\']").click()
    assert "Teton Turf and Tree" in self.driver.find_element(By.TAG_NAME, "body").text
  
  def test_homePageBasics(self):
    self.driver.get("http://localhost:5500/teton/1.6/index.html")
    self.driver.set_window_size(1200, 800)
    elements = self.driver.find_elements(By.CSS_SELECTOR, "header img")
    assert len(elements) > 0
    assert "Teton Idaho" in self.driver.find_element(By.CSS_SELECTOR, "h1").text
    assert self.driver.title == "Teton Idaho CoC"
  
  def test_homeSpotlightsJoinLink(self):
    self.driver.get("http://localhost:5500/teton/1.6/index.html")
    self.driver.set_window_size(1200, 800)
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight1 img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".spotlight2 img")
    assert len(elements) > 0
    elements = self.driver.find_elements(By.LINK_TEXT, "Join Us!")
    assert len(elements) > 0
    self.driver.find_element(By.LINK_TEXT, "Join Us!").click()
  
  def test_directoryGridTest(self):
    self.driver.get("http://localhost:5500/teton/1.6/directory.html")
    self.driver.set_window_size(1200, 800)
    self.driver.find_element(By.ID, "directory-grid").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, "body")
    assert len(elements) > 0
  
  def test_adminBadLoginError(self):
    self.driver.get("http://localhost:5500/teton/1.6/admin.html")
    self.driver.set_window_size(1200, 800)
    elements = self.driver.find_elements(By.ID, "username")
    assert len(elements) > 0
    self.driver.find_element(By.ID, "username").click()
    elements = self.driver.find_elements(By.ID, "password")
    assert len(elements) > 0
    self.driver.find_element(By.NAME, "password").click()
    elements = self.driver.find_elements(By.CSS_SELECTOR, ".myinput:nth-child(2)")
    assert len(elements) > 0
    self.driver.find_element(By.CSS_SELECTOR, ".myinput:nth-child(2)").click()
  
  def test_joinFormStep1Step2(self):
    self.driver.get("http://localhost:5500/teton/1.6/join.html")
    self.driver.set_window_size(1200, 800)
    self.driver.find_element(By.NAME, "fname").send_keys("Aaron")
    self.driver.find_element(By.NAME, "lname").send_keys("Gravelle")
    self.driver.find_element(By.NAME, "bizname").send_keys("Techtronics Solutions")
    self.driver.find_element(By.NAME, "biztitle").send_keys("CEO")
    self.driver.find_element(By.NAME, "submit").click()
    assert self.driver.find_element(By.NAME, "email")


  
